CREATE TABLE tmember(
	userId VARCHAR2(6),
	userPw VARCHAR2(12) NOT NULL,
	userName VARCHAR2(30) NOT NULL,
	phoneNum VARCHAR2(30) NOT NULL,
	email VARCHAR2(100),
	sex VARCHAR2(12),
	regdate DATE DEFAULT SYSDATE,
	updateDate DATE DEFAULT SYSDATE,
	keepItem VARCHAR2(300),
	likenum VARCHAR2(300),
	level NUMBER DEFAULT 2,
	CONSTRAINT tmember_pk_userId PRIMARY KEY(userId)
)

CREATE TABLE tmember(
userId VARCHAR2(6) PRIMARY KEY,
userPw VARCHAR2(12) NOT NULL,
userName VARCHAR2(30) NOT NULL,
phoneNum VARCHAR2(30) NOT NULL,
email VARCHAR2(100),
sex VARCHAR2(12),
regdate DATE DEFAULT SYSDATE,
updateDate DATE DEFAULT SYSDATE,
keepItem VARCHAR2(300),
likeItem VARCHAR2(300),
levelCount NUMBER DEFAULT 2
)


SELECT * FROM tmember
DROP TABLE tmember