CREATE TABLE tmember(
userId VARCHAR2(6) PRIMARY KEY,
userPw VARCHAR2(12) NOT NULL,
userName VARCHAR2(30) NOT NULL,
phoneNum VARCHAR2(30) NOT NULL,
email VARCHAR2(100) NOT NULL,
sex VARCHAR2(12) NOT NULL,
regdate DATE DEFAULT SYSDATE,
updateDate DATE DEFAULT SYSDATE,
keepItem VARCHAR2(300),
likeItem VARCHAR2(300),
levelCount NUMBER DEFAULT 2
)


SELECT * FROM tmember
DROP TABLE tmember